package io.app.modal;

public enum Industry {
    AGRICULTURE,
    MANUFACTURING,
    CONSTRUCTION,
    RETAIL,
    FINANCIAL_SERVICES,
    HEALTHCARE,
    INFORMATION_TECHNOLOGY,
    TELECOMMUNICATIONS,
    REAL_ESTATE,
    TRANSPORTATION
}
